name: smart_travel_planner
description: "Smart travel planner"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
      
  #State management
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

  #Navigation
  go_router: ^14.6.3

  #Network
  dio: ^5.7.0

  #Database
  drift: ^2.23.1
  drift_flutter: ^0.2.4

  #Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  #Logger
  logging: ^1.3.0
  clock: ^1.1.1

  #UI
  google_maps_flutter: ^2.10.0

  #Utils
  location: ^6.0.2
  internet_connection_checker: ^3.0.1
  rxdart: ^0.28.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  drift_dev: ^2.23.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/map.json
